### ISSUE TITLE
HMR breaks CSS hot reload

### ISSUE THREAD

**Issue by mario-jerkovic** [faceyspacey/babel-plugin-dual-import#3]
Hey there!  😃 

Maybe this is not the place for this issue (maybe it is) but here it is...
I have encountered a bug when you change something inside a component HMR will trigger and the component will be updated, but if you that change the .css for the same component new style tag will be injected just the component wont apply those new styles...

I've seen that the component when it first mounts "injects" the link tag 
```javascript
<link href="http://localhost:3000/DashboardPage.css" charset="utf-8" type="text/css" rel="stylesheet">
```
and if the HMR occurs it replaces it with the new one like:
```javascript
<link href="http://localhost:3000/DashboardPage.css?1501963084820" charset="utf-8" type="text/css" rel="stylesheet">
```
but for some reason if you change the component code than the css the initial link tag will be still in DOM it will just prepend the new (HOT)

![alt text](https://gifyu.com/images/issue3dd2e.gif)

**EXAMPLE:** Here is the repo that reflects the issue (master-branch) [REPO](https://github.com/mario-jerkovic/boilerplate-react)

**BTW:** Thanks for this awesome suite of components/lib's 🍺

**Comment by faceyspacey** [comment]
I found the problem. It's that `importCss` is being called on HMR, when it shouldn't be. 

React Universal Component will require synchronously once the chunk reaches the client. And because the synchronous code path is used, the `Promise.all` importJs+Css stuff won't be called again. 

Here's what's causing it:

1) You have react-universal-component in your autodll. Synchronous "weak" resolving/requiring does not work there. 
2) However, even if it wasn't in the autdll config, you're not providing the `resolve` option to your `universal` components. Therefore  `universal` wouldn't be able to resolve synchronously anyway. 

> NOTE: If you use `babel-plugin-universal-import` that was launched on Friday, it will automatically add the resolve option for you: https://medium.com/faceyspacey/announcing-react-universal-component-2-0-babel-plugin-universal-import-5702d59ec1f4 ...I tried it along with removing RUC from the autodll config and it solves your HMR issue.

I know you're not doing SSR (yet at least), but providing the `resolve` option is also helpful on the client, for the aforementioned reason and others.

Now, that said, both babel plugins can be improved so that the CSS isn't imported again. Each chunk name could be marked as true once imported, and `importCss.js` could simply resolve without doing anything in that case. I'm super overloaded right now, but a PR would be welcome.

...check this:

```js
const routes = {
    DASHBOARD: 'DashboardPage',
    PROFILE: 'ProfilePage',
    REVIEWS: 'ReviewsPage',
    NOTIFICATIONS: 'NotificationsPage',
};

const UniversalComponent = universal(({ Component }) => import(`./${Component}/index.js`), {
    minDelay: 500,
    error: NotFoundPage,
});

export default ({ page }) => { // eslint-disable-line react/prop-types
    const Component = routes[page];

    return (
        <div>
            <UniversalComponent Component={Component} />
        </div>
    );
};
```

you can use just one component now. You gotta use the fork `webpack-universal`. I was actually going do a PR to your repo, but realized that i couldn't use `module-alias` to alias it since you're using `webpack-dev-server`. Either way, in a few days, the latest webpack will be published to NPM which will allow this. Check the above linked article for more details.

Stoked you're enjoying the toolset. Hit me any time.

**Comment by faceyspacey** [comment]
also, if it's not clear, basically dual-import is only for people not using react-universal-component. universal-import is now the new hotness :)

**Comment by mario-jerkovic** [comment]
@faceyspacey Thanks you for the detailed response 👍   that was very helpful...

Unfortunately there are couple of reasons why on my work project I cannot use SSR, that why it's not implemented in the example repo.. but to overcome the limitation with the ```__CSS_CHUNKS__``` used by the babel-plugin I have made a small webpack plugin that injects the ```__CSS_CHUNKS__``` in the window using the webpack stats... (i know it's Hacky but it works pretty well :D )

About the dynamic import (they are awesome): I have tried it (struggled) and finally realized that you have made a PR to webpack to resolve that issue and that is not "released" yet and yes I cannot use your fork of webpack because I am using webpack-dev-server... I will wait few day unit new version of webpack is released

**Comment by faceyspacey** [comment]
I saw that. very nice. You should open source that, and I'll recommend it in one of the docs.

**Comment by mario-jerkovic** [comment]
Sure thing.. will PM you when I release it
