### ISSUE TITLE
Remove deprecated attributes and add preload

### ISSUE THREAD

**Issue by sshrshnv** [faceyspacey/babel-plugin-dual-import#7]
@faceyspacey what about remove `charset` and `type` attributes for `link` and `script` tags? 
They are not needed for html5.
And it's good to add `preload`

**Comment by faceyspacey** [comment]
I just copied what webpack was doing when they inject dynamic imports. 

I'm not sure charset and type will make much difference removing them. As for `preload`, that also seems irrelevant since these links are only added to the page after initial load:

https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content

I could be wrong though.
